# Yelp Business rating prediction

In [7]:
import pandas as pd
import os
import json

business=[]
with open('yelp_academic_dataset_business.json') as f:
    for line in f:
        business.append(json.loads(line))
business_df=pd.DataFrame.from_dict(business)

reviews=[]
with open('yelp_academic_dataset_review.json') as f:
    for line in f:
        reviews.append(json.loads(line))
reviews_df=pd.DataFrame.from_dict(reviews)

In [13]:
print(business_df.shape)
print(reviews_df.shape)

(188593, 15)
(5996996, 9)


In [14]:
pd.set_option('display.max_colwidth',-1)

## Column description

In [15]:
print(business_df.columns)
print(reviews_df.columns)

Index(['address', 'attributes', 'business_id', 'categories', 'city', 'hours',
       'is_open', 'latitude', 'longitude', 'name', 'neighborhood',
       'postal_code', 'review_count', 'stars', 'state'],
      dtype='object')
Index(['business_id', 'cool', 'date', 'funny', 'review_id', 'stars', 'text',
       'useful', 'user_id'],
      dtype='object')


In [32]:
business_df.head(5)

address  \
0  1314 44 Avenue NE     
1                        
2  1335 rue Beaubien E   
3  211 W Monroe St       
4  2005 Alyth Place SE   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   attributes  \
0  {'BikeParking': 'False', 'BusinessAcceptsCreditCards': 'True', 'BusinessParking': '{'garage': False, 'street': True, 'validated': False, 'lot': False, 'valet': False}', 'GoodForKids': 'True', 'HasTV': 'True', 'NoiseLevel': 'average', 'OutdoorSeating': 'False', 'RestaurantsAttire': 'casual', 'RestaurantsDelivery': 'False', 'RestaurantsGoodForGroups': 'True', 'RestaurantsPriceRange2': '2', 'RestaurantsReservations': 'True', 'RestaurantsTakeOut': 'True'}                                                                                                                                                                                                                                                                                                                                                                                                      
1  {'Alcohol': 'none', 'BikeParking': 'False', 'BusinessAcceptsCreditCards': 'True', 'BusinessParking': '{'garage': False, 'street': True, 'validated': False, 'lot': True, 'valet': False}', 'Caters': 'True', 'DogsAllowed': 'True', 'DriveThru': 'False', 'GoodForKids': 'True', 'GoodForMeal': '{'dessert': False, 'latenight': False, 'lunch': False, 'dinner': False, 'breakfast': False, 'brunch': False}', 'HasTV': 'False', 'OutdoorSeating': 'True', 'RestaurantsAttire': 'casual', 'RestaurantsDelivery': 'False', 'RestaurantsGoodForGroups': 'True', 'RestaurantsPriceRange2': '2', 'RestaurantsReservations': 'False', 'RestaurantsTableService': 'False', 'RestaurantsTakeOut': 'True', 'WheelchairAccessible': 'True', 'WiFi': 'no'}                                                                                                                            
2  {'Alcohol': 'beer_and_wine', 'Ambience': '{'romantic': False, 'intimate': False, 'classy': False, 'hipster': False, 'touristy': False, 'trendy': False, 'upscale': False, 'casual': False}', 'BikeParking': 'True', 'BusinessAcceptsCreditCards': 'False', 'BusinessParking': '{'garage': False, 'street': False, 'validated': False, 'lot': False, 'valet': False}', 'Caters': 'False', 'GoodForKids': 'True', 'GoodForMeal': '{'dessert': False, 'latenight': False, 'lunch': False, 'dinner': False, 'breakfast': False, 'brunch': False}', 'HasTV': 'True', 'NoiseLevel': 'average', 'OutdoorSeating': 'False', 'RestaurantsAttire': 'casual', 'RestaurantsDelivery': 'False', 'RestaurantsGoodForGroups': 'True', 'RestaurantsPriceRange2': '2', 'RestaurantsReservations': 'True', 'RestaurantsTableService': 'True', 'RestaurantsTakeOut': 'False', 'WiFi': 'free'}   
3  None                                                                                                                                                                                                                                                                                                                                                                                                                                                                       

In [68]:
reviews_df.head(1)

business_id  cool        date  funny               review_id  \
0  iCQpiavjjPzJ5_3gPD5Ebg  0     2011-02-25  0      x7mDIiDB3jEiPGPHOmDzyw   

   stars  \
0  2       

                                                                                                                                                                                                                                                                                                                                                                                                                                                                text  \
0  The pizza was okay. Not the best I've had. I prefer Biaggio's on Flamingo / Fort Apache. The chef there can make a MUCH better NY style pizza. The pizzeria @ Cosmo was over priced for the quality and lack of personality in the food. Biaggio's is a much better pick if youre going for italian - family owned, home made recipes, people that actually CARE if you like their food. You dont get that at a pizzeria in a casino. I dont care what you say...   

   useful                 user_id  
0  0       msQe1u7Z_XuqjGoqhB0J5g

### Datatypes

In [27]:
reviews_df.dtypes

business_id    object
cool           int64 
date           object
funny          int64 
review_id      object
stars          int64 
text           object
useful         int64 
user_id        object
dtype: object

In [30]:
business_df.isnull().sum()

address         0    
attributes      25786
business_id     0    
categories      541  
city            0    
hours           44802
is_open         0    
latitude        6    
longitude       6    
name            0    
neighborhood    0    
postal_code     0    
review_count    0    
stars           0    
state           0    
dtype: int64

In [31]:
reviews_df.isnull().sum()

business_id    0
cool           0
date           0
funny          0
review_id      0
stars          0
text           0
useful         0
user_id        0
dtype: int64

In [57]:
review_df_agg=reviews_df.groupby('business_id')['text'].sum()

In [59]:
review_df_for_sklearn=pd.DataFrame({'business_id':review_df_agg.index,'all_reviews':review_df_agg.values})

In [94]:
review_business=pd.merge(review_df_for_sklearn,business_df,on='business_id',how='left')

In [139]:
review_business.shape

(188593, 16)

In [140]:
review_business_sample=review_business.sample(frac=.10)
print(review_business_sample.shape)

(18859, 16)


In [141]:
review_business_sample.head(1)
review_business_sample.dtypes

business_id     object 
all_reviews     object 
address         object 
attributes      object 
categories      object 
city            object 
hours           object 
is_open         int64  
latitude        float64
longitude       float64
name            object 
neighborhood    object 
postal_code     object 
review_count    int64  
stars           float64
state           object 
dtype: object

### Numeric column Normalization

In [146]:
from scipy.stats import zscore

review_count_normalized=zscore(review_business_sample['review_count'])
review_count_normalized.shape #normalized review_count

(18859,)

### TF-IDF Vectorzation

In [147]:
import sklearn.feature_extraction.text as sk_text
vectorizer=sk_text.TfidfVectorizer(stop_words='english',max_features=1000,min_df=2)
matrix=vectorizer.fit_transform(review_business_sample['all_reviews'])

print(type(matrix))
print(matrix.toarray())

#print(vectorizer.get_feature_names())

<class 'scipy.sparse.csr.csr_matrix'>
[[0.         0.10551563 0.         ... 0.         0.         0.        ]
 [0.         0.0163873  0.02368761 ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.0110482  0.         ... 0.         0.         0.        ]
 [0.         0.01756878 0.00586048 ... 0.00406469 0.00750796 0.01730025]
 [0.         0.01738353 0.         ... 0.         0.         0.        ]]


In [153]:
tfif_data=matrix.toarray()


In [154]:
tfif_data.shape

(18859, 1000)

In [155]:
import numpy as np
concat_matrix=np.column_stack((tfif_data,review_count_normalized))
concat_matrix

array([[ 0.        ,  0.10551563,  0.        , ...,  0.        ,
         0.        , -0.25495366],
       [ 0.        ,  0.0163873 ,  0.02368761, ...,  0.        ,
         0.        , -0.16696556],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        , -0.25495366],
       ...,
       [ 0.        ,  0.0110482 ,  0.        , ...,  0.        ,
         0.        , -0.03498342],
       [ 0.        ,  0.01756878,  0.00586048, ...,  0.00750796,
         0.01730025,  1.48721061],
       [ 0.        ,  0.01738353,  0.        , ...,  0.        ,
         0.        , -0.04378223]])

In [156]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [159]:
X=concat_matrix
y=review_business_sample['stars']

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=.2,random_state =1)
#print(X_train.shape)
#print(X_test.shape)

(15087, 1001)
(3772, 1001)


### Linear Regression Model

In [191]:
lr=LinearRegression()
lr.fit(X_train,y_train)
y_pred_train=lr.predict(X_train)
#print('Train RMSE:')
#print(np.sqrt(metrics.mean_squared_error(y_train,y_pred_train)))

y_pred_test=lr.predict(X_test)
print(y_pred_test)
print(y)
#print('Test RMSE:')
#print(np.sqrt(metrics.mean_squared_error(y_test,y_pred_test)))

[6.96717604 4.61848455 6.00835214 ... 1.39085727 6.61401682 6.83437318]
[7 4 1 ... 3 7 1]


#### Label Encoding

In [170]:
import pandas as pd
import numpy as np
import os , io
from sklearn.model_selection import train_test_split
from sklearn import preprocessing

le = preprocessing.LabelEncoder()
le.fit(review_business_sample['stars'])

list(le.classes_)

y = le.transform(review_business_sample['stars'])

#### Train and Test Split

In [194]:
X_train, X_test,y_train,y_test = train_test_split(concat_matrix,y,test_size=0.25,random_state=1)

### Support Vector Machine model

In [195]:
from sklearn.svm import SVC

clf = SVC()
clf.fit(X_train,y_train)
y_train_pred=clf.predict(X_train)
y_test_pred=clf.predict(X_test)
type(y_train_pred)
print(y_test_pred)
#print('Train RMSE:')
#print(np.sqrt(metrics.mean_squared_error(y_train,y_train_pred)))
#print('Test RMSE:')
#print(np.sqrt(metrics.mean_squared_error(y_test,y_test_pred)))


[6 6 8 ... 8 6 8]


In [196]:
print(y)

[7 4 1 ... 3 7 1]


### KNeighbor classifier

In [189]:
#knn classfrom sklearn.neighbors import KNeighborsClassifierifier
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=1)
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.3,random_state=0)

knn.fit(X_train, y_train)
y_train_pred=knn.predict(X_train)
y_test_pred=knn.predict(X_test)
type(y_train_pred)
#print('Train RMSE:')
#print(np.sqrt(metrics.mean_squared_error(y_train,y_train_pred)))
#print('Test RMSE:')
#print(np.sqrt(metrics.mean_squared_error(y_test,y_test_pred)))
print(y_test_pred)
print(y)

[6 6 5 ... 4 8 6]
[7 4 1 ... 3 7 1]


### Logistic Regression

In [188]:
#logistic Regression

# import the class
from sklearn.linear_model import LogisticRegression

# instantiate the model (using the default parameters)
logreg = LogisticRegression()

# fit the model with data
logreg.fit(X_train, y_train)
y_train_pred=logreg.predict(X_train)
y_test_pred=logreg.predict(X_test)
type(y_train_pred)
print(y_test_pred)
print(y)
#print('Train RMSE:')
#print(np.sqrt(metrics.mean_squared_error(y_train,y_train_pred)))
#print('Test RMSE:')
#print(np.sqrt(metrics.mean_squared_error(y_test,y_test_pred)))

[8 5 6 ... 3 6 8]
[7 4 1 ... 3 7 1]


In [207]:
minmax=review_business_sample['review_count'].max()-review_business_sample['review_count'].min()
nmn_reviewcount=(review_business_sample['review_count']-review_business_sample['review_count'].min())/minmax
nmn_rc_nparray=nmn_reviewcount.values
nmn_rc_nparray.shape
import numpy as np
concat_matrix=np.column_stack((tfif_data,nmn_rc_nparray))
X=concat_matrix

### Multinomial navies Bayes

In [208]:
from sklearn.naive_bayes import MultinomialNB
clf=MultinomialNB()
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.3,random_state=0)

clf.fit(X_train,y_train)
y_train_pred=clf.predict(X_train)
y_test_pred=clf.predict(X_test)
type(y_train_pred)
print(y_test_pred)
print(y)

[8 5 6 ... 3 6 8]
[7 4 1 ... 3 7 1]
